# Generated by Django 4.2.8 on 2024-03-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
